var myString = "Hello, World!";
var myNumber = 42;
var myBoolean = true;
var myNull = null;
let myUndefined;

console.log(myString);
console.log(myNumber);
console.log(myBoolean);
console.log(myNull);
console.log(myUndefined);

console.log(typeof myString);
console.log(typeof myNumber);
console.log(typeof myBoolean);
console.log(typeof myNull);
console.log(typeof myUndefined);

const firstName = "Yousef";
const lastName = "Eldeeb";

const fullNameOld = firstName + " " + lastName;
console.log(fullNameOld);

const fullNameNew = `${firstName} ${lastName}`;
console.log(fullNameNew);